### ISSUE TITLE
Alternate version with 3D sword models that match the icon more accurately?

### ISSUE THREAD

**Issue by Zortabre** [TimmyChips/Pommel-Held-Item-Models#1]
Hello, I love this pack but I'm a bit bothered by the way that the swords look. I would like to move the top-right pixel down to the left side to make the sword more even and have a pointed end in the middle rather than on one side, but I do not have the technical knowledge to make edits to a 3D pack like this. Would it be possible for you to make another version with an alternate sword model?

**Comment by TimmyChips** [comment]
Sure I can do that! I don't have to change anything to the mod so I can make an extra version of the resource pack with the modified sword models.

Just to make sure you want the sword to be perfectly symmetrical, just like this, with a pointed tip? 
![Mirrored Sword Example](https://i.imgur.com/EnLQhtR.png)

**Comment by Zortabre** [comment]
Yes, that looks perfect!

**Comment by TimmyChips** [comment]
Alright, here's a version of the sword blades symmetrical just like that. Here's the [Modrinth page](https://modrinth.com/resourcepack/blade-held-items/version/Symmetrical-Swords_1.0.1).

Thanks again for the suggestion!

**Comment by Zortabre** [comment]
Awesome, thank you so much!
